# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Instaurant' do
    pod 'Box', '~>2.0'
    pod 'Result', '0.6.0-beta.3'
    pod 'SimpleAuth/Instagram', '~>0.3.9'
end


